####################################################################
#**************************** USER ROUTES **************************
####################################################################

### GET ALL USERS
GET http://localhost:3001/users
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjksInVzZXJuYW1lIjoicG9wZSIsImVtYWlsIjoicGlua0BkZW1vLmNvbSIsImlhdCI6MTYwNjM3NzAwMiwiZXhwIjoxNjA2NDIwMjAyfQ.msTpKjiqw6cgjqmT31LNXvXBsNaWQ8s5pubSJjx7QY0"
}

### POST ROUTE ADD NEW USER
POST http://localhost:3001/users
Content-Type: application/json

{
  "username": "banana",
  "password": "banana",
  "firstname": "Banana",
  "lastname": "Monkey",
  "email": "monkey@banana.com"
}

# {
#   "username": "john",
#   "password": "john",
#   "firstname": "John",
#   "lastname": "Conner",
#   "email": "john@conner.com"
# }

# {
#   "username": "chicken",
#   "password": "chicken",
#   "firstname": "Chicken",
#   "lastname": "LongLegs",
#   "email": "test@test.com"
# }

### LOGIN ROUTE
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "billy",
  "password": "billy"
}

### UPDATE USER
PATCH http://localhost:3001/users/6
Content-Type: application/json

{
  "password": "john",
  "firstname": "JOHN",
  "lastname": "CONNER",
  "email": "john@conner.com",
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJqb2huIiwiZW1haWwiOiJqb2huQGNvbm5lci5jb20iLCJpYXQiOjE2MDUyMTQzMzYsImV4cCI6MTYwNTI1NzUzNn0.OJrD4b0ZqqT_sOXyUWn55k72kjVuLVsOHlu--vWakNo"
}

### GET ONE USER
GET http://localhost:3001/users/31
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzEsInVzZXJuYW1lIjoidGVzdCIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsImlhdCI6MTYwNjM4MTEzNywiZXhwIjoxNjA2NDI0MzM3fQ.piYkf_1q3tLG6AIwmZV20BvcxeDyk8HaZ9EKZ8gXr5s"
}

### DELETE SINGLE USER
DELETE http://localhost:3001/users/29
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjksInVzZXJuYW1lIjoicG9wZSIsImVtYWlsIjoicG9wZUBkZW1vLmNvbSIsImlhdCI6MTYwNjM3OTMzMSwiZXhwIjoxNjA2NDIyNTMxfQ.dOyqVTNwV_bbudhghFSDK3jHnUoFnvCVMjwVzEX_mwY"
}

####################################################################
#*************************** MOVIES ROUTES *************************
####################################################################

### ADD MOVIE TO DB
POST http://localhost:3001/movies/add
Content-Type: application/json

# {
#   "title": "Roald Dahl's The Witches",
#     "description": "In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the world's Grand High Witch has gathered.",
#     "rating": 7,
#     "id": 531219,
#     "image": "/betExZlgK0l7CZ9CsCBVcwO1OjL.jpg",
#     "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBkZW1vLmNvbSIsImlhdCI6MTYwNjI4OTMyMiwiZXhwIjoxNjA2MzMyNTIyfQ.v0oHADgPlCUd6eNbsvKs8P8TYbbPohKKRQyfe6xwqrA"
# }

# {
#   "title": "The Shawshank Redemption",
#     "description": "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
#     "rating": 8.7,
#     "id": 278,
#     "image": "/5KCVkau1HEl7ZzfPsKAPM0sMiKc.jpg",
#     "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBkZW1vLmNvbSIsImlhdCI6MTYwNjI4OTMyMiwiZXhwIjoxNjA2MzMyNTIyfQ.v0oHADgPlCUd6eNbsvKs8P8TYbbPohKKRQyfe6xwqrA"
# }
# {
#   "title": "Schindler's List",
#     "description": "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
#     "rating": 8.6,
#     "id": 424,
#     "image": "/c8Ass7acuOe4za6DhSattE359gr.jpg",
#     "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBkZW1vLmNvbSIsImlhdCI6MTYwNjI4OTMyMiwiZXhwIjoxNjA2MzMyNTIyfQ.v0oHADgPlCUd6eNbsvKs8P8TYbbPohKKRQyfe6xwqrA"
# }
# {
#   "title": "Terminator: Dark Fate",
#     "description": "Decades after Sarah Connor prevented Judgment Day, a lethal new Terminator is sent to eliminate the future leader of the resistance. In a fight to save mankind, battle-hardened Sarah Connor teams up with an unexpected ally and an enhanced super soldier to stop the deadliest Terminator yet.",
#     "rating": 6.5,
#     "id": 290859,
#     "image": "/vqzNJRH4YyquRiWxCCOH0aXggHI.jpg",
#     "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBkZW1vLmNvbSIsImlhdCI6MTYwNjI4OTMyMiwiZXhwIjoxNjA2MzMyNTIyfQ.v0oHADgPlCUd6eNbsvKs8P8TYbbPohKKRQyfe6xwqrA"
# }
{
  "title": "Terminator 2: Judgment Day",
    "description": "Decades after Sarah Connor prevented Judgment Day, a lethal new Terminator is sent to eliminate the future leader of the resistance. In a fight to save mankind, battle-hardened Sarah Connor teams up with an unexpected ally and an enhanced super soldier to stop the deadliest Terminator yet.",
    "rating": 8,
    "id": 8697,
    "image": "/5M0j0B18abtBI5gi2RhfjjurTqb.jpg",
    "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBkZW1vLmNvbSIsImlhdCI6MTYwNjI4OTMyMiwiZXhwIjoxNjA2MzMyNTIyfQ.v0oHADgPlCUd6eNbsvKs8P8TYbbPohKKRQyfe6xwqrA"
}

### GET MOVIE BY ID FROM DATABASE
GET http://localhost:3001/movies/99999
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBkZW1vLmNvbSIsImlhdCI6MTYwNjIyMTY3OSwiZXhwIjoxNjA2MjY0ODc5fQ.QmC8LxWIAlEomhq6yGkbpomFqR_bxv5hkCoS0DUH2C8"
}

### GET ALL MOVIES FROM DATABASE
GET http://localhost:3001/movies/
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBkZW1vLmNvbSIsImlhdCI6MTYwNjMzNjE5NywiZXhwIjoxNjA2Mzc5Mzk3fQ.dt5kiDqchuugJe-3xcPvufPLpA9euWXPVDebzf9PPDA"
}

### REMOVE MOVIE BY ID FROM DATABASE
DELETE http://localhost:3001/movies/741074
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzIsInVzZXJuYW1lIjoiYmlsbHkiLCJlbWFpbCI6ImJpbGx5QGdvbGRlbnN3b3JkLmNvbSIsImlhdCI6MTYwNjQyMzA1NywiZXhwIjoxNjA2NDY2MjU3fQ.QvuPEGWzViARd9EgCCAJsAVyK1xDg5PDyCjFuSZFQnI"
}

####################################################################
#************************* WATCHLIST ROUTES ************************
####################################################################

### ADD MOVIE TO WATCHLIST (TOKEN REQUIRED)
POST http://localhost:3001/watchlist/21/add
Content-Type: application/json

{
  "movie_id": 424,
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsInVzZXJuYW1lIjoiamFuZSIsImVtYWlsIjoiamFuZUBkb2UuY29tIiwiaWF0IjoxNjA2MjkwMTE0LCJleHAiOjE2MDYzMzMzMTR9.aLoSelb-TUh2JQ73kSlvayBzxb3LjpY_dPola0_7c_4"
}

### GET MOVIE FROM WATCHLIST (TOKEN REQUIRED)
GET http://localhost:3001/watchlist/20
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoiam9obiIsImVtYWlsIjoiam9obkBkZW1vLmNvbSIsImlhdCI6MTYwNjMzNjE5NywiZXhwIjoxNjA2Mzc5Mzk3fQ.dt5kiDqchuugJe-3xcPvufPLpA9euWXPVDebzf9PPDA"
}


### REMOVE MOVIE FROM WATCHLIST (TOKEN REQUIRED)
DELETE http://localhost:3001/watchlist/6/531219
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJqb2huIiwiZW1haWwiOiJqb2huQGNvbm5lci5jb20iLCJpYXQiOjE2MDUyMTY5MDEsImV4cCI6MTYwNTI2MDEwMX0.bqSU4rN5JAeAYzI8QigiUQIHMix00cUNj4c5BxMPR0E"
}

####################################################################
#************************* MOVIE API ROUTES ************************
####################################################################

### GET POPULAR MOVIES
GET http://localhost:3001/api/popular
Content-Type: application/json

### GET TOP RATED MOVIES
GET http://localhost:3001/api/toprated
Content-Type: application/json

### GET MOVIES BY CATEGORY (comedy, action)
GET http://localhost:3001/api/comedy
Content-Type: application/json

### GET MOVIES BY ID
GET http://localhost:3001/api/531219
Content-Type: application/json

### GET MOVIE CREDIT BY ID
GET http://localhost:3001/api/credits/531219
Content-Type: application/json

### SEARCH FOR A MOVIE
GET http://localhost:3001/api/search/terminator
Content-Type: application/json