####################################################################
#**************************** USER ROUTES **************************
####################################################################

### GET ALL USERS
GET http://localhost:3001/users
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJlbWFpbCI6ImpvaG5AY29ubmVyLmNvbSIsImlhdCI6MTYwNDc0NzQyNywiZXhwIjoxNjA0NzkwNjI3fQ.glBqW_RTyvZoIBCofBdF87JF-St_5rsQ-k-eSD7DjJ0"
}

### POST ROUTE ADD NEW USER
POST http://localhost:3001/users
Content-Type: application/json

# {
#   "username": "banana",
#   "password": "banana",
#   "firstname": "Banana",
#   "lastname": "Monkey",
#   "email": "monkey@banana.com"
# }

# {
#   "username": "john",
#   "password": "john",
#   "firstname": "John",
#   "lastname": "Conner",
#   "email": "john@conner.com",
#   "is_admin": false
# }

{
  "username": "chicken",
  "password": "chicken",
  "firstname": "Chicken",
  "lastname": "LongLegs",
  "email": "test@test.com",
  "is_admin": true
}

### LOGIN ROUTE
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "john",
  "password": "john"
}

### UPDATE USER
PATCH http://localhost:3001/users/banana
Content-Type: application/json

{
  "password": "banana",
  "firstname": "Banana",
  "lastname": "UpsideDown",
  "email": "monkey@test.com",
 "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbmFuYSIsImVtYWlsIjoibW9ua2V5QGJhbmFuYS5jb20iLCJpYXQiOjE2MDQ1Nzc1MzUsImV4cCI6MTYwNDYyMDczNX0.tV2E3b0IM-1njZfEb6qVHT_BvxitiQDmvlQoTNxT7so"
}

### GET ONE USER
GET http://localhost:3001/users/banana
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbmFuYSIsImVtYWlsIjoibW9ua2V5QGJhbmFuYS5jb20iLCJpYXQiOjE2MDQ1Nzc1MzUsImV4cCI6MTYwNDYyMDczNX0.tV2E3b0IM-1njZfEb6qVHT_BvxitiQDmvlQoTNxT7so"
}

### DELETE SINGLE USER
DELETE http://localhost:3001/users/chicken
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inphbmdvb2NoIiwiZW1haWwiOiJ6YXlkQGdtYWlsLmNvbSIsImlzX2FkbWluIjp0cnVlLCJpYXQiOjE2MDM4MzAzODEsImV4cCI6MTYwMzg3MzU4MX0.NuWIAE0XWuNNpcst-xdRifmo7081eh6Y4hW171qi05Q"
}

####################################################################
#*************************** MOVIES ROUTES *************************
####################################################################

### ADD MOVIE TO DB
POST http://localhost:3001/movies/add
Content-Type: application/json

{
  "id": 337401,
  "title": "Mulan",
  "description": "When the Emperor of China issues a decree that one man per family must serve in the Imperial Chinese Army to defend the country from Huns, Hua Mulan, the eldest daughter of an honored warrior, steps in to take the place of her ailing father. She is spirited, determined and quick on her feet. Disguised as a man by the name of Hua Jun, she is tested every step of the way and must harness her innermost strength and embrace her true potential.",
  "image": "https://api.themoviedb.org/3/movies/337401/images/zzWGRw277MNoCs3zhyG3YmYQsXv.jpg",
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJlbWFpbCI6ImpvaG5AY29ubmVyLmNvbSIsImlhdCI6MTYwNDc0NzQyNywiZXhwIjoxNjA0NzkwNjI3fQ.glBqW_RTyvZoIBCofBdF87JF-St_5rsQ-k-eSD7DjJ0"
}

### GET MOVIE BY ID FROM DATABASE
GET http://localhost:3001/movies/337401
Content-Type: application/json

####################################################################
#************************* WATCHLIST ROUTES ************************
####################################################################

### ADD MOVIE TO WATCHLIST (TOKEN REQUIRED)
POST http://localhost:3001/watchlist/3/add
Content-Type: application/json

{
  "movie_id": 337401,
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJlbWFpbCI6ImpvaG5AY29ubmVyLmNvbSIsImlhdCI6MTYwNDc0NzQyNywiZXhwIjoxNjA0NzkwNjI3fQ.glBqW_RTyvZoIBCofBdF87JF-St_5rsQ-k-eSD7DjJ0"
}

### GET MOVIE FROM WATCHLIST (TOKEN REQUIRED)
GET http://localhost:3001/watchlist/1
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJlbWFpbCI6ImpvaG5AY29ubmVyLmNvbSIsImlhdCI6MTYwNDc0NzQyNywiZXhwIjoxNjA0NzkwNjI3fQ.glBqW_RTyvZoIBCofBdF87JF-St_5rsQ-k-eSD7DjJ0"
}

### REMOVE MOVIE FROM WATCHLIST (TOKEN REQUIRED)
DELETE http://localhost:3001/watchlist/3/337401
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJlbWFpbCI6ImpvaG5AY29ubmVyLmNvbSIsImlhdCI6MTYwNDc0NzQyNywiZXhwIjoxNjA0NzkwNjI3fQ.glBqW_RTyvZoIBCofBdF87JF-St_5rsQ-k-eSD7DjJ0"
}

####################################################################
#************************* MOVIE API ROUTES ************************
####################################################################

### GET POPULAR MOVIES
GET http://localhost:3001/api/popular
Content-Type: application/json

### GET TOP RATED MOVIES
GET http://localhost:3001/api/toprated
Content-Type: application/json

### GET MOVIES BY CATEGORY (comedy, action)
GET http://localhost:3001/api/action
Content-Type: application/json

### GET SIMILAR MOVIES BY ID
GET http://localhost:3001/api/337401
Content-Type: application/json
