####################################################################
#**************************** USER ROUTES **************************
####################################################################

### GET ALL USERS
GET http://localhost:3001/users
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbmFuYSIsImVtYWlsIjoibW9ua2V5QGJhbmFuYS5jb20iLCJpYXQiOjE2MDUyMDkyOTYsImV4cCI6MTYwNTI1MjQ5Nn0.GfeR1I1yXKIqJoOn9wDWFOG0d_ShLLjpdQxhbDfsulI"
}

### POST ROUTE ADD NEW USER
POST http://localhost:3001/users
Content-Type: application/json

{
  "username": "banana",
  "password": "banana",
  "firstname": "Banana",
  "lastname": "Monkey",
  "email": "monkey@banana.com"
}

# {
#   "username": "john",
#   "password": "john",
#   "firstname": "John",
#   "lastname": "Conner",
#   "email": "john@conner.com"
# }

# {
#   "username": "chicken",
#   "password": "chicken",
#   "firstname": "Chicken",
#   "lastname": "LongLegs",
#   "email": "test@test.com"
# }

### LOGIN ROUTE
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "john",
  "password": "john"
}

### UPDATE USER
PATCH http://localhost:3001/users/6
Content-Type: application/json

{
  "password": "john",
  "firstname": "JOHN",
  "lastname": "CONNER",
  "email": "john@conner.com",
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJqb2huIiwiZW1haWwiOiJqb2huQGNvbm5lci5jb20iLCJpYXQiOjE2MDUyMTQzMzYsImV4cCI6MTYwNTI1NzUzNn0.OJrD4b0ZqqT_sOXyUWn55k72kjVuLVsOHlu--vWakNo"
}

### GET ONE USER
GET http://localhost:3001/users/6
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJqb2huIiwiZW1haWwiOiJqb2huQGNvbm5lci5jb20iLCJpYXQiOjE2MDUyMTMwMjAsImV4cCI6MTYwNTI1NjIyMH0.N2G5MeBhAl1hNRV0-C45xSbQbIX4N08T4nXRfy6Tlx4"
}

### DELETE SINGLE USER
DELETE http://localhost:3001/users/5
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJiYW5hbmEiLCJlbWFpbCI6Im1vbmtleUBiYW5hbmEuY29tIiwiaWF0IjoxNjA1MjEzMjc2LCJleHAiOjE2MDUyNTY0NzZ9.ldsTxASWrFnV6cxZWNUTq6Oba8igWpQePBx1AENhS2I"
}

####################################################################
#*************************** MOVIES ROUTES *************************
####################################################################

### ADD MOVIE TO DB
POST http://localhost:3001/movies/add
Content-Type: application/json

# {
#   "title": "Roald Dahl's The Witches",
#     "description": "In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the world's Grand High Witch has gathered.",
#     "rating": 7,
#     "id": 531219,
#     "image": "/betExZlgK0l7CZ9CsCBVcwO1OjL.jpg",
#     "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoaWNrZW4iLCJlbWFpbCI6ImNoaWNrZW5AdGVzdC5jb20iLCJpYXQiOjE2MDUwNzg5MTQsImV4cCI6MTYwNTEyMjExNH0.x1lYE93GskST1lbE0UBTLjMe8rL1aRAuc_5mS11lMNQ"
# }
{
  "title": "ANOTHER TEST movie added to DB",
    "description": "Lorem ipsum",
    "rating": 7,
    "id": 99999,
    "image": "/betExZlgK0l7CZ9CsCBVcwO1OjL.jpg",
    "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJqb2huIiwiZW1haWwiOiJqb2huQGNvbm5lci5jb20iLCJpYXQiOjE2MDUyMTQzMzYsImV4cCI6MTYwNTI1NzUzNn0.OJrD4b0ZqqT_sOXyUWn55k72kjVuLVsOHlu--vWakNo"
}

### GET MOVIE BY ID FROM DATABASE
GET http://localhost:3001/movies/99999
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJqb2huIiwiZW1haWwiOiJqb2huQGNvbm5lci5jb20iLCJpYXQiOjE2MDUyMTQzMzYsImV4cCI6MTYwNTI1NzUzNn0.OJrD4b0ZqqT_sOXyUWn55k72kjVuLVsOHlu--vWakNo"
}

### GET ALL MOVIES FROM DATABASE
GET http://localhost:3001/movies/
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJqb2huIiwiZW1haWwiOiJqb2huQGNvbm5lci5jb20iLCJpYXQiOjE2MDUyMTQzMzYsImV4cCI6MTYwNTI1NzUzNn0.OJrD4b0ZqqT_sOXyUWn55k72kjVuLVsOHlu--vWakNo"
}

####################################################################
#************************* WATCHLIST ROUTES ************************
####################################################################

### ADD MOVIE TO WATCHLIST (TOKEN REQUIRED)
POST http://localhost:3001/watchlist/6/add
Content-Type: application/json

{
  "movie_id": 531219,
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJqb2huIiwiZW1haWwiOiJqb2huQGNvbm5lci5jb20iLCJpYXQiOjE2MDUyMTY5MDEsImV4cCI6MTYwNTI2MDEwMX0.bqSU4rN5JAeAYzI8QigiUQIHMix00cUNj4c5BxMPR0E"
}

### GET MOVIE FROM WATCHLIST (TOKEN REQUIRED)
GET http://localhost:3001/watchlist/6
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJqb2huIiwiZW1haWwiOiJqb2huQGNvbm5lci5jb20iLCJpYXQiOjE2MDUyMTY5MDEsImV4cCI6MTYwNTI2MDEwMX0.bqSU4rN5JAeAYzI8QigiUQIHMix00cUNj4c5BxMPR0E"
}


### REMOVE MOVIE FROM WATCHLIST (TOKEN REQUIRED)
DELETE http://localhost:3001/watchlist/6/531219
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlcm5hbWUiOiJqb2huIiwiZW1haWwiOiJqb2huQGNvbm5lci5jb20iLCJpYXQiOjE2MDUyMTY5MDEsImV4cCI6MTYwNTI2MDEwMX0.bqSU4rN5JAeAYzI8QigiUQIHMix00cUNj4c5BxMPR0E"
}

####################################################################
#************************* MOVIE API ROUTES ************************
####################################################################

### GET POPULAR MOVIES
GET http://localhost:3001/api/popular
Content-Type: application/json

### GET TOP RATED MOVIES
GET http://localhost:3001/api/toprated
Content-Type: application/json

### GET MOVIES BY CATEGORY (comedy, action)
GET http://localhost:3001/api/comedy
Content-Type: application/json

### GET MOVIES BY ID
GET http://localhost:3001/api/531219
Content-Type: application/json

### GET MOVIE CREDIT BY ID
GET http://localhost:3001/api/credits/531219
Content-Type: application/json

### SEARCH FOR A MOVIE
GET http://localhost:3001/api/search/terminator
Content-Type: application/json