### GET
GET http://localhost:3001/api/popular
Content-Type: application/json

# {
#   "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJlbWFpbCI6ImpvaG5AY29ubmVyLmNvbSIsImlhdCI6MTYwNDczNzY0OSwiZXhwIjoxNjA0NzgwODQ5fQ.W2PzIkWTrdmSKZP1NNeyh_Uu5RiInUJTteWbKDLEur8"
# }

###GET CATEGORY
GET http://localhost:3001/api/toprated
Content-Type: application/json


###GET TOPRATED
GET http://localhost:3001/api/toprated
Content-Type: application/json

###GET CATEGORY
GET http://localhost:3001/api/action
Content-Type: application/json


### POST NEW ORDER
POST http://localhost:3000/orders/chicken/new
Content-Type: application/json

{
  "id": 1,
  "user_id": 1,
  "cart_id": 1,
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoaWNrZW4iLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjA0MTQ5ODYzLCJleHAiOjE2MDQxOTMwNjN9.JYA2yYrIT8CKku-Z25UsTQyJhW4dTWfaEsth9n2GH_Q"
}


###GET SIMILAR
GET http://localhost:3001/api/similar
Content-Type: application/json

{
  "movie_id": 424
}

### get single
GET http://localhost:3001/api/items/3
Content-Type: application/json

### update single
PUT http://localhost:3001/api/items/4
Content-Type: application/json

{
  "title": "Updated Item",
  "price": 20,
  "description": "lorem ipsum something something",
  "category": "toys"
}

### GET BY ID
GET http://localhost:3001/api/424
Content-Type: application/json


### GET FROM API
GET https://api.upcitemdb.com/prod/trial/lookup?upc=0885909950805
Content-Type: application/json

### GET UPC
GET http://localhost:3001/api/upc
Content-Type: application/json
