### GET ALL
GET http://localhost:3001/users
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoaWNrZW4iLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjA0MjQwMzIyLCJleHAiOjE2MDQyODM1MjJ9.O4aKMxqu4HAclf2womf2BJ2njB-bSvM9ELdmEAACmjQ"
}

### POST USER ADD NEW USER
POST http://localhost:3001/users
Content-Type: application/json

{
  "username": "banana",
  "password": "banana",
  "firstname": "Banana",
  "lastname": "Monkey",
  "email": "monkey@banana.com",
  "is_admin": false
}

# {
#   "username": "john",
#   "password": "john",
#   "firstname": "John",
#   "lastname": "Conner",
#   "email": "john@conner.com",
#   "is_admin": false
# }

# {
#   "username": "chicken",
#   "password": "chicken",
#   "firstname": "Chicken",
#   "lastname": "LongLegs",
#   "email": "test@test.com",
#   "is_admin": true
# }
### Zayd Token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InpheWQiLCJlbWFpbCI6InpheWRAZ21haWwuY29tIiwiaXNfYWRtaW4iOnRydWUsImlhdCI6MTYwMzk0NjM0NiwiZXhwIjoxNjAzOTg5NTQ2fQ.3VFthfmkCB0vnQG8TfbdZ9XUpQWY6VAqNl_t1IfkTfQ"

### LOGIN
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "chicken",
  "password": "chicken"
}

### UPDATE
PATCH http://localhost:3000/users/chicken
Content-Type: application/json

{
  "password": "chicken",
  "firstname": "Chicken",
  "lastname": "ShortLegs",
  "email": "test@test.com",
 "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoaWNrZW4iLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjA0MDU1NjQwLCJleHAiOjE2MDQwOTg4NDB9.8bHhYJVv-2MZm7a0Gon9Lyv3mCquYzLjFbBanBHLv6Y"
}

### GET ONE
GET http://localhost:3001/users/chicken
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoaWNrZW4iLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpc19hZG1pbiI6dHJ1ZSwiaWF0IjoxNjA0MjU2NDUyLCJleHAiOjE2MDQyOTk2NTJ9.ixlFgk8GcEu3BzdnJ7LNGbX4teLKKfefx7cqK55Vcd4"
}

### DELETE USER
DELETE http://localhost:3001/users/chicken
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inphbmdvb2NoIiwiZW1haWwiOiJ6YXlkQGdtYWlsLmNvbSIsImlzX2FkbWluIjp0cnVlLCJpYXQiOjE2MDM4MzAzODEsImV4cCI6MTYwMzg3MzU4MX0.NuWIAE0XWuNNpcst-xdRifmo7081eh6Y4hW171qi05Q"
}