### GET ALL
GET http://localhost:3001/users
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJlbWFpbCI6ImpvaG5AY29ubmVyLmNvbSIsImlhdCI6MTYwNDc0NzQyNywiZXhwIjoxNjA0NzkwNjI3fQ.glBqW_RTyvZoIBCofBdF87JF-St_5rsQ-k-eSD7DjJ0"
}

### POST USER ADD NEW USER
POST http://localhost:3001/users
Content-Type: application/json

# {
#   "username": "banana",
#   "password": "banana",
#   "firstname": "Banana",
#   "lastname": "Monkey",
#   "email": "monkey@banana.com"
# }

# {
#   "username": "john",
#   "password": "john",
#   "firstname": "John",
#   "lastname": "Conner",
#   "email": "john@conner.com",
#   "is_admin": false
# }

{
  "username": "chicken",
  "password": "chicken",
  "firstname": "Chicken",
  "lastname": "LongLegs",
  "email": "test@test.com",
  "is_admin": true
}
### Zayd Token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InpheWQiLCJlbWFpbCI6InpheWRAZ21haWwuY29tIiwiaXNfYWRtaW4iOnRydWUsImlhdCI6MTYwMzk0NjM0NiwiZXhwIjoxNjAzOTg5NTQ2fQ.3VFthfmkCB0vnQG8TfbdZ9XUpQWY6VAqNl_t1IfkTfQ"

### LOGIN
POST http://localhost:3001/login
Content-Type: application/json

{
  "username": "john",
  "password": "john"
}

### UPDATE
PATCH http://localhost:3001/users/banana
Content-Type: application/json

{
  "password": "banana",
  "firstname": "Banana",
  "lastname": "UpsideDown",
  "email": "monkey@test.com",
 "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbmFuYSIsImVtYWlsIjoibW9ua2V5QGJhbmFuYS5jb20iLCJpYXQiOjE2MDQ1Nzc1MzUsImV4cCI6MTYwNDYyMDczNX0.tV2E3b0IM-1njZfEb6qVHT_BvxitiQDmvlQoTNxT7so"
}

### GET ONE
GET http://localhost:3001/users/banana
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhbmFuYSIsImVtYWlsIjoibW9ua2V5QGJhbmFuYS5jb20iLCJpYXQiOjE2MDQ1Nzc1MzUsImV4cCI6MTYwNDYyMDczNX0.tV2E3b0IM-1njZfEb6qVHT_BvxitiQDmvlQoTNxT7so"
}

### DELETE USER
DELETE http://localhost:3001/users/chicken
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inphbmdvb2NoIiwiZW1haWwiOiJ6YXlkQGdtYWlsLmNvbSIsImlzX2FkbWluIjp0cnVlLCJpYXQiOjE2MDM4MzAzODEsImV4cCI6MTYwMzg3MzU4MX0.NuWIAE0XWuNNpcst-xdRifmo7081eh6Y4hW171qi05Q"
}

### ADD TO WATCHLIST
POST http://localhost:3001/watchlist/3/add
Content-Type: application/json

{
  "movie_id": 874658374
}

### GET FROM WATCHLIST
GET http://localhost:3001/watchlist/1
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJlbWFpbCI6ImpvaG5AY29ubmVyLmNvbSIsImlhdCI6MTYwNDc0NzQyNywiZXhwIjoxNjA0NzkwNjI3fQ.glBqW_RTyvZoIBCofBdF87JF-St_5rsQ-k-eSD7DjJ0"
}

### ADD MOVIE TO DB
POST http://localhost:3001/movies/add
Content-Type: application/json

{
  "id": 874658374,
  "title": "fake movie",
  "rating": 3.7,
  "image": "https://api.themoviedb.org/3/movies/337401/images?api_key=a19fde14eb2f33b545cd78125e338397/zzWGRw277MNoCs3zhyG3YmYQsXv.jpg",
  "description": "Lorem Ipsum Lorem ipsum again",
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJlbWFpbCI6ImpvaG5AY29ubmVyLmNvbSIsImlhdCI6MTYwNDc0NzQyNywiZXhwIjoxNjA0NzkwNjI3fQ.glBqW_RTyvZoIBCofBdF87JF-St_5rsQ-k-eSD7DjJ0"
}

### REMOVE MOVIE FROM WATCHLIST
DELETE http://localhost:3001/watchlist/3/874658374
Content-Type: application/json

{
  "_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4iLCJlbWFpbCI6ImpvaG5AY29ubmVyLmNvbSIsImlhdCI6MTYwNDYxMTUyMCwiZXhwIjoxNjA0NjU0NzIwfQ.JnCN9jwoFeRJHTMri9OGq5yOEfiYY2PA7HnK6hM5C1Q"
}